# Generated by Django 5.2.5 on 2025-09-01 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('mcq', 'Multiple choice (single)'), ('checkbox', 'Multiple choice (multiple)')], default='text', max_length=16)),
                ('category', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='self_analysis.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SelfAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('combined_positives', models.JSONField(blank=True, default=dict)),
                ('combined_negatives', models.JSONField(blank=True, default=dict)),
                ('quote', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_analysis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('polarity', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=8)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_value', models.FloatField(default=0.0)),
                ('max_value', models.FloatField(default=100.0)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['polarity', 'is_active'], name='self_analys_polarit_f1971e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='self_analysis.question')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('question', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('positive_values', models.JSONField(blank=True, default=dict)),
                ('negative_values', models.JSONField(blank=True, default=dict)),
                ('quote', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='self_analysis.question')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'question'], name='self_analys_user_id_d235db_idx'), models.Index(fields=['question'], name='self_analys_questio_3173f4_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
